version: 2

jobs:
  prepareinstall4j:
    docker:
      - image: circleci/openjdk:11.0.3-jdk-stretch
    steps:
      - checkout
      - restore_cache:
          keys:
            - install4j-{{ checksum "scripts/prepare-install4j.sh" }}
      - run: scripts/prepare-install4j.sh
      - save_cache:
          key: install4j-{{ checksum "scripts/prepare-install4j.sh" }}
          paths:
            - "~/.install4j8"
    filters:
      tags:
        only: /.*/

  buildDev:
    docker:
      - image: circleci/openjdk:11.0.4-jdk-stretch
    steps:
      - checkout
      - restore_cache:
          key: install4j-{{ checksum "scripts/prepare-install4j.sh" }}
      - run: scripts/prepare-install4j.sh
      - run: install4j8/bin/install4jc --verbose --license=$INSTALL4J8_KEY
      - restore_cache:
          key: gradle
      - run: git submodule sync
      - run: git submodule update --init
      - run: ./gradlew -Pdev=true -Pinstall4jDir="install4j8" release --stacktrace
      - run: ./gradlew jlink
      - run: mv build/image jabref
      - run: tar cvzf JabRef-linux-${CIRCLE_BRANCH}-latest.tar.gz jabref
      - run: mv JabRef-latest.tar.gz build/releases/
      - save_cache:
          key: gradle
          paths:
            - "~/.gradle"
      - store_artifacts:
          path: build/releases
          destination: build
      - run: scripts/upload-to-builds.jabref.org.sh

  buildRelease:
    docker:
      - image: circleci/openjdk:11.0.4-jdk-stretch
    steps:
      - checkout
      - restore_cache:
          key: install4j-{{ checksum "scripts/prepare-install4j.sh" }}
      - run: scripts/prepare-install4j.sh
      - run: install4j8/bin/install4jc --verbose --license=$INSTALL4J8_KEY
      - restore_cache:
          key: gradle
      - run: git submodule sync
      - run: git submodule update --init
      - run: ./gradlew -Pinstall4jDir="install4j8" release --stacktrace
      - store_artifacts:
          path: build/releases
          destination: release
      - run: scripts/upload-to-builds.jabref.org.sh
    filters:
      tags:
        only: /.*/

workflows:
  version: 2
  build:
    jobs:
      - prepareinstall4j
      - buildDev:
          requires:
            - prepareinstall4j
      - buildRelease:
          requires:
            - prepareinstall4j
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
