# Configuration for https://dependabot.com
version: 1

update_configs:
  - package_manager: "java:gradle"
    directory: "/"
    update_schedule: "weekly"
    default_labels:
      - "dependencies"
    automerged_updates:
      - match:
         dependency_type: "all"
         update_type: "semver:minor"
            
  - package_manager: "submodules"
    directory: "/"
    update_schedule: "weekly"
    default_labels:
      - "dependencies"
    automerged_updates:
      - match:
         dependency_type: "all"
         update_type: "all"
