name: Assign Issue

on:
  schedule:
    - cron: 0 0 * * *
  issue_comment:
    types: [created]
  workflow_dispatch:

jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - name: Assign the user or unassign stale assignments
        uses: takanome-dev/assign-issue-action@refactor-rewrite-action
        with:
          github_token: '${{ secrets.GITHUB_TOKEN }}'
          days_until_unassign: 30
          assigned_comment: |
            ğŸ‘‹ Hey @{{ handle }},

            Thanks for your interest in this issue! ğŸ‰

            Newcomers, we're excited to have you on board. Start by exploring our [Contributing](https://github.com/JabRef/jabref/blob/main/CONTRIBUTING.md) guidelines, and don't forget to check out our [workspace setup guidelines](https://devdocs.jabref.org/getting-into-the-code/guidelines-for-setting-up-a-local-workspace) to get started smoothly.

            In case you encounter failing tests during development, please check our [developer FAQs](https://devdocs.jabref.org/code-howtos/faq.html)!

            Having any questions or issues? Feel free to ask here on GitHub. Need help setting up your local workspace? Join the conversation on [JabRef's Gitter chat](https://gitter.im/JabRef/jabref). And don't hesitate to open a (draft) pull request early on to show the direction it is heading towards. This way, you will receive valuable feedback.

            Note that you will be unassigned if it isn't closed within **{{ total_days }} days** (**{{ unassigned_date }}**).

            > [!NOTE]
            > A maintainer can also add the **{{ pin_label }}** label to prevent it from being unassigned automatically.

            Happy coding! ğŸš€
