name: Cleanup after PR

on:
  pull_request:
    types: [closed]

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
      - name: Check secrets presence
        id: checksecrets
        shell: bash
        run: |
          if [ "$BUILDJABREFPRIVATEKEY" == "" ]; then
            run: echo "secretspresent=false" >> $GITHUB_OUTPUT
          else
            run: echo "secretspresent=true" >> $GITHUB_OUTPUT
          fi
        env:
          BUILDJABREFPRIVATEKEY: ${{ secrets.buildJabRefPrivateKey }}
      - name: Extract branch name
        id: extract_branch
        if: ${{ steps.checksecrets.outputs.secretspresent }}
        run: |
          echo "branch=${{ github.event.pull_request.head.ref }}" >> $GITHUB_OUTPUT
      - name: Delete folder on builds.jabref.org
        if: ${{ steps.checksecrets.outputs.secretspresent }}
        uses: appleboy/ssh-action@v0.1.5
        with:
          script: rm -rf /var/www/builds.jabref.org/www/${{ steps.extract_branch.outputs.branch }} || true
          host: build-upload.jabref.org
          port: 9922
          username: jrrsync
          key: ${{ secrets.buildJabRefPrivateKey }}
