name: On issue unassigned

on:
  issues:
     types:
       - unassigned

jobs:
  columns_and_labels:
    if: ${{ github.repository_owner == 'JabRef' }}
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: read
    steps:
      - uses: actions/checkout@v5
      - name: Check assignees
        id: check_assignee
        run: |
          issue=$(gh issue view ${{ github.event.issue.number }} --json assignees)
          count=$(echo "$issue" | jq '.assignees | length')
          if [ "$count" -gt 0 ]; then
            echo "assigned=yes" >> $GITHUB_OUTPUT
          else
            echo "assigned=no" >> $GITHUB_OUTPUT
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Move Issue to "Free to take" Column in "Candidates for University Projects"
        if: steps.check_assignee.outputs.assigned == 'no'
        uses: m7kvqbe1/github-action-move-issues@main
        with:
          github-token: ${{ secrets.GH_TOKEN_ACTION_MOVE_ISSUE }}
          project-url: "https://github.com/orgs/JabRef/projects/3"
          target-labels: ""
          target-column: "Free to take"
          ignored-columns: ""
          default-column: "Free to take"
          skip-if-not-in-project: true
      - name: Move Issue to "Free to take" Column in "Good First Issues"
        if: steps.check_assignee.outputs.assigned == 'no'
        uses: m7kvqbe1/github-action-move-issues@main
        with:
          github-token: ${{ secrets.GH_TOKEN_ACTION_MOVE_ISSUE }}
          project-url: "https://github.com/orgs/JabRef/projects/5"
          target-labels: ""
          target-column: "Free to take"
          ignored-columns: ""
          default-column: "Free to take"
          skip-if-not-in-project: true
      - name: Remove labels assigned, reminder-sent, pinned, and "FirstTimeCodeContribution"
        if: steps.check_assignee.outputs.assigned == 'no'
        run: |
          set -e

          gh issue edit ${{ github.event.issue.number }} --remove-label "üìç Assigned"
          gh issue edit ${{ github.event.issue.number }} --remove-label "üîî reminder-sent"
          gh issue edit ${{ github.event.issue.number }} --remove-label "üìå Pinned"
          gh issue edit ${{ github.event.issue.number }} --remove-label "FirstTimeCodeContribution"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
