name: On issue unlabeled

on:
  issues:
     types:
       - unlabeled

jobs:
  handle_Assigned_and_FirstTimeCodeContribution:
    name: "ğŸ“ Assigned or FirstTimeCodeContribution"
    if: ${{ (github.event.label.name == 'ğŸ“ Assigned' || github.event.label.name == 'FirstTimeCodeContribution') && github.repository_owner == 'JabRef' }}
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Move Issue to "Free to take" Column in "Candidates for University Projects"
        uses: m7kvqbe1/github-action-move-issues@main
        with:
          github-token: ${{ secrets.GH_TOKEN_ACTION_MOVE_ISSUE }}
          project-url: "https://github.com/orgs/JabRef/projects/3"
          target-labels: "ğŸ“ Assigned"
          target-column: "Assigned"
          ignored-columns: ""
          default-column: "Free to take"
          skip-if-not-in-project: true
      - name: Move Issue to "Free to take" Column in "Good First Issues"
        uses: m7kvqbe1/github-action-move-issues@main
        with:
          github-token: ${{ secrets.GH_TOKEN_ACTION_MOVE_ISSUE }}
          project-url: "https://github.com/orgs/JabRef/projects/5"
          target-labels: "ğŸ“ Assigned"
          target-column: "Assigned"
          ignored-columns: ""
          default-column: "Free to take"
          skip-if-not-in-project: true
      - uses: actions/checkout@v6
      - name: Remove all assignees
        run: |
          ASSIGNEES=$(gh issue view ${{ github.event.issue.number }} --json assignees --template '{{range .assignees}}{{.login}} {{end}}')
          for user in $ASSIGNEES; do
            gh issue edit ${{ github.event.issue.number }} --remove-assignee "$user"
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Remove labels assigned, reminder-sent, pinned, and "FirstTimeCodeContribution"
        run: |
          set -e

          gh issue edit ${{ github.event.issue.number }} --remove-label "ğŸ“ Assigned"
          gh issue edit ${{ github.event.issue.number }} --remove-label "ğŸ”” reminder-sent"
          gh issue edit ${{ github.event.issue.number }} --remove-label "ğŸ“Œ Pinned"
          gh issue edit ${{ github.event.issue.number }} --remove-label "FirstTimeCodeContribution"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
