name: Welcome a first-time contributor

on:
  pull_request_target:
    types: [opened]

jobs:
  welcome-first-time-contributor:
    if: github.repository == 'JabRef/jabref'
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: plbstl/first-contribution@v4
        with:
          labels: first contrib
          pr-opened-msg: >
            ### Hey @{fc-author}!


            Thank you for contributing to JabRef! Your help is truly appreciated :heart:.


            We have automatic checks in place, based on which you will soon get automated feedback if any of them are failing.
            Later on in the review process, one of our maintainers will also go through your contribution.
            In the "Files changed" tab, you can go through its comments and just click on "Resolve conversation" if you are sure that it is incorrect, or comment on the conversation if you are doubtful.


            Please re-check our [contribution guide](https://github.com/JabRef/jabref/blob/main/CONTRIBUTING.md) in case of any other doubts related to our contribution workflow.
