name: Label merge-queue PR

on:
  merge_group:

jobs:
  label:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: 'Add label "status: to-be-merged"'
        run: |
          gh pr edit ${{ github.event.merge_group.pull_request.number }} --add-label "status: to-be-merged"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
