name: Product Map Generation

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  generate-map:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 100

      - name: Get changed Java files
        id: changed-files
        run: |
          FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} -- '*.java' | sed 's|^|\"|' | sed 's|$|\"|' | paste -sd "," -)
          if [ -z "$FILES" ]; then FILES="\"dummy.java\""; fi
          echo "expected_files=(${FILES})" >> $GITHUB_ENV
          echo "Files: ${FILES}"

      - name: ProductMap Map Generation
        uses: product-map/product-map-action@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          expected_files: ${{ env.expected_files }}
          user_email: koppdev@gmail.com
