name: Rerun PR merge conflicts check

on:
  schedule:
    - cron: "0 3 * * *"
  pull_request:
    paths:
      - '.github/workflows/rerun-merge-conflict-check.yml'
  workflow_dispatch:

jobs:
  rerun:
    if: github.repository == 'JabRef/jabref'
    runs-on: ubuntu-slim
    permissions:
      actions: write
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v6
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: jq
          version: 1.0
      - name: Trigger "On PR opened/updated (check)" for all open PRs
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          workflow_name="On PR opened/updated (check)"

          gh pr list --state open --json number --jq '.[] | "\(.number)"' |
          while read pr; do
            echo "Triggering '$workflow_name' for PR #$pr"
            gh workflow run "$workflow_name" --ref main --field pr_number="$pr"
            echo "Triggered '$workflow_name' for PR [#$pr](https://github.com/JabRef/jabref/pull/$pr)" >> $GITHUB_STEP_SUMMARY
            sleep 3
          done
