name: Snap

on:
  workflow_dispatch:
  push:
    branches:
      - snapcraft
  schedule:
   # run on each day
  - cron: "33 4 * * *"

concurrency:
  group: snap-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    name: Create snapcraft image
    steps:
      - name: Check secrets presence
        id: checksecrets
        shell: bash
        run: |
          if [ "$SNAPCRAFT_LOGIN_FILE" == "" ]; then
            run: echo "secretspresent=false" >> $GITHUB_OUTPUT
          else
            run: echo "secretspresent=true" >> $GITHUB_OUTPUT
          fi
        env:
          SNAPCRAFT_LOGIN_FILE: ${{ secrets.SNAPCRAFT_LOGIN_FILE }}
      - name: Checkout source
        uses: actions/checkout@v3
      # The image relies on https://builds.jabref.org/master/JabRef-5.0-portable_linux.tar.gz^
      # See snap/snapcraft.yml for details
      - name: Run snapcraft build
        uses: snapcore/action-build@v1
        id: snapcraft
        with:
          snapcraft-args: "--debug"
      - name: Upload snap
        if: ${{ steps.checksecrets.outputs.secretspresent }}
        uses: snapcore/action-publish@v1
        with:
          store_login: ${{ secrets.SNAPCRAFT_LOGIN_FILE }}
          snap: ${{ steps.snapcraft.outputs.snap }}
          release: edge
