name: Mark stale issues and pull requests

on:
  schedule:
  - cron: "20 19 * * *"

jobs:
  stale:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/stale@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        days-before-stale: 180
        days-before-close: 14
        stale-issue-message: |
          This issue has been inactive for half a year. Since JabRef is constantly evolving this issue may not be relevant any longer and it will be closed in two weeks if no further activity occurs.

          As part of an effort to ensure that the JabRef team is focusing on important and valid issues, we would like to ask if you could update the issue if it still persists. This could be in the following form:

          - If there has been a longer discussion, add a short summary of the most important points as a new comment (if not yet existing).
          - Provide further steps or information on how to reproduce this issue.
          - Upvote the initial post if you like to see it implemented soon. Votes are not the only metric that we use to determine the requests that are implemented, however, they do factor into our decision-making process.
          - If all information is provided and still up-to-date, then just add a short comment that the issue is still relevant.

          Thank you for your contribution!
        stale-issue-label: 'status: stale'
