name: Fetcher Tests

on:
  push:
    branches:
      - main
    paths:
      - 'src/main/java/org/jabref/logic/importer/fetcher/**'
      - 'src/test/java/org/jabref/logic/importer/fetcher/**'
      - '.github/workflows/tests-fetchers.yml'
      - 'build.gradle'
  pull_request:
    paths:
      - 'src/main/java/org/jabref/logic/**'
      - 'src/test/java/org/jabref/logic/**'
      - 'src/main/java/org/jabref/model/**'
      - 'src/test/java/org/jabref/model/**'
      - '.github/workflows/tests-fetchers.yml'
      - 'build.gradle'
  schedule:
    # run on each Wednesday
    - cron: '2 3 * * 3'
  workflow_dispatch:

env:
  SpringerNatureAPIKey: ${{ secrets.SPRINGERNATUREAPIKEY_FOR_TESTS }}
  AstrophysicsDataSystemAPIKey: ${{ secrets.AstrophysicsDataSystemAPIKey_FOR_TESTS }}
  IEEEAPIKey: ${{ secrets.IEEEAPIKey_FOR_TESTS }}

concurrency:
  group: fetcher-tests-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  fetchertests:
    name: Fetcher tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: 16
          distribution: 'adopt'
          cache: 'gradle'
      - name: Run fetcher tests
        run: ./gradlew fetcherTest
        env:
          CI: "true"
