name: Fetcher Tests

on:
  push:
    branches:
      - main
    paths:
      - 'src/main/java/org/jabref/logic/importer/fetcher/**'
      - 'src/test/java/org/jabref/logic/importer/fetcher/**'
      - 'src/main/java/org/jabref/logic/importer/fileformat/PdfMergeMetadataImporter.java'
      - 'src/test/java/org/jabref/logic/importer/fileformat/PdfMergeMetadataImporterTest.java'
      - 'src/main/java/org/jabref/logic/crawler/**'
      - 'src/test/java/org/jabref/logic/crawler/**'
      - '.github/workflows/tests-fetchers.yml'
      - 'build.gradle'
  pull_request:
    paths:
      - 'src/main/java/org/jabref/logic/importer/fetcher/**'
      - 'src/test/java/org/jabref/logic/importer/fetcher/**'
      - 'src/main/java/org/jabref/logic/importer/fileformat/PdfMergeMetadataImporter.java'
      - 'src/test/java/org/jabref/logic/importer/fileformat/PdfMergeMetadataImporterTest.java'
      - 'src/main/java/org/jabref/logic/crawler/**'
      - 'src/test/java/org/jabref/logic/crawler/**'
      - '.github/workflows/tests-fetchers.yml'
      - 'build.gradle'
  schedule:
    # run on each Monday
    - cron: '2 3 * * 1'
  workflow_dispatch:

env:
  BiodiversityHeritageApiKey: ${{ secrets.BiodiversityHeritageApiKey_FOR_TESTS }}
  AstrophysicsDataSystemAPIKey: ${{ secrets.AstrophysicsDataSystemAPIKey_FOR_TESTS }}
  IEEEAPIKey: ${{ secrets.IEEEAPIKey_FOR_TESTS }}
  MedlineApiKey: ${{ secrets.MedlineApiKey_FOR_TESTS }}
  SpringerNatureAPIKey: ${{ secrets.SPRINGERNATUREAPIKEY_FOR_TESTS }}

concurrency:
  group: "${{ github.workflow }}-${{ github.head_ref || github.ref }}"
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  fetchertests:
    if: github.repository == 'JabRef/jabref' || github.event_name != 'schedule'
    name: Fetcher tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v5
        with:
          submodules: 'true'
          show-progress: 'false'
      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: 24
          distribution: 'corretto'
          check-latest: true
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
      - name: Generate JBang cache key
        id: cache-key
        shell: bash
        run: |
          echo "cache_key=jbang-$(date +%Y-%m)" >> $GITHUB_OUTPUT
      - name: Use cache
        uses: actions/cache/restore@v4
        with:
          path: ~/.jbang
          key: ${{ steps.cache-key.outputs.cache_key }}
          restore-keys:
            jbang-
      - name: Setup JBang
        uses: jbangdev/setup-jbang@main
      - name: Run fetcher tests
        run: ./gradlew fetcherTest
        env:
          CI: "true"
